[package]
name = "ndmig"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.20.1"
tokio = { version = "1", features = ["full"] }
clearscreen = "4.0.5"
colored = "3.1.1"
futures-util = "0.3"
